// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.model;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieApp.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250516081917_FinalRenaming")]
    partial class FinalRenaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.model.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .HasColumnType("integer")
                        .HasColumnName("GenreID");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("GenreName");

                    b.HasKey("GenreID")
                        .HasName("Genre_pkey");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("MovieApp.model.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("integer")
                        .HasColumnName("MovieID");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("Duration");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Genre");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Language");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Overview");

                    b.Property<string>("Posterpath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Posterpath");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("Rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Title");

                    b.HasKey("MovieID")
                        .HasName("Movie_pkey");

                    b.ToTable("Movie", (string)null);
                });

            modelBuilder.Entity("MovieApp.model.Usermaster", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Firstname");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("Gender");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Password");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("UserTypeName");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Username");

                    b.HasKey("UserID")
                        .HasName("Usermaster_pkey");

                    b.ToTable("Usermaster", (string)null);
                });

            modelBuilder.Entity("MovieApp.model.Usertype", b =>
                {
                    b.Property<int>("UserTypeID")
                        .HasColumnType("integer")
                        .HasColumnName("UserTypeID");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("UserTypeName");

                    b.HasKey("UserTypeID")
                        .HasName("UserType_pkey");

                    b.ToTable("Usertype", (string)null);
                });

            modelBuilder.Entity("MovieApp.model.Watchlist", b =>
                {
                    b.Property<string>("WatchlistID")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("WatchlistID");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DateCreated");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("WatchlistID")
                        .HasName("Watchlist_pkey");

                    b.ToTable("Watchlist", (string)null);
                });

            modelBuilder.Entity("MovieApp.model.WatchlistItems", b =>
                {
                    b.Property<int>("WatchlistItemID")
                        .HasColumnType("integer")
                        .HasColumnName("WatchlistItemID");

                    b.Property<int>("MovieID")
                        .HasColumnType("integer")
                        .HasColumnName("MovieID");

                    b.Property<string>("WatchlistID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("WatchlistID");

                    b.HasKey("WatchlistItemID")
                        .HasName("WatchlistItems_pkey");

                    b.ToTable("\"WatchlistItems\"", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
